### ISSUE TITLE
additional data for meaningful reports

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH-Reporter#1]
- for reasonable reports we may need more data than yet stored in LOSH
- however, the approach of basing the whole report on queries on LOSH data is very convenient

→ Would it be possible to extent fetchers (after a yet to be written specification from my side) so that they would get more data and store it into RDF? We would however don't change anything in the Wikibase module → data will appear solely in RDF (getting this data to the Frontend is subject to a larger change within the LOSH system). I could simply define the keys and update the ontology; however, I'd like to have your opinion on this first :)

**Comment by hoijui** [comment]
We now use RDF as data-source anyway, so .. done! :-)
