### ISSUE TITLE
LOSH Report Feedback | Round 1

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH-Reporter#13]
Thousand thanks to @MIE5R0 and Jan from TUB for the super rich feedback on the report! I'm attaching their commented version of the first report to this issue for reference.

Here's a ToDo list of points to resolve that I extracted from their comments and from a video call with them. All points are for @moedn unless otherwise stated

- [x] add a "Limitations" section outlining current known issues
  - no historical data (would require changes of the crawler)
  - no location data available (available from some platforms, but would require changes of the crawler)
  - no platform-specific metadata available (would require changes of the crawler)
  - only hardware licensing considered; no data about diverging documentation licenses (or licenses of involved software)
- [x] add clarification that OSH flagship recommendations have been taken from the OPEN!NEXT and OSEG community
- [x] add a mention of relevant metadata fields to the diagrams to create a connection in the report
- [x] mention which OSH flagships can be found on LOSH (ODRL3*) (and hence are part of the dataset) (add link to LOSH)
- [x] explain ODRL/OTRL (table with criteria per level) + link publication
- [x] add a explanatory comment to the ODRL/OTRL diagram (why so little scattering?)
- [ ] <s>add a ODRL/OTRL diagram without Thingiverse @hoijui</s>
- [x] add detail graphic of misc licenses only (which includes CERN) @hoijui
- [x] add explanation on CPC → why was CPC used instead of e.g. OSHWA categories?
- [x] add mapping to CPC categories as annex (or link them) (maybe @hoijui)
- [x] link definition of LOD + outline how LOSH data qualifies for 5 of 5 stars of LOD
- [x] add a mention of selection criteria of the supported platforms (copy from D3.4 report)
- [x] descending order of categories in the legends (e.g. fig:repo-hosts-percent) @hoijui 
- [ ] <s>add support for image captions and cross-references
    (yet only the "unrendered code" appears in the doc) @hoijui</s>
    -> tried to do that already -> not possible/too cumbersome
  - <s>maybe by using [pandoc-xnos](https://github.com/tomduck/pandoc-xnos)?</s> -> we are using jupyter, not pandoc
- [ ] <s>possible to substitute 2.4.1 graphics with a heatmap? @hoijui</s>
- [x] delete ch. 2.2.2
- [x] explain small number of projects (64) in the subset 2.4.2
- [x] Give a rough estimate of how much of the OSH universe is represented in the LOSH data (and indicate the improvement over OSHWA data)
- [x] Make a short verbal description of the statistical outcomes (i.e. distribution of readiness levels)
- [x] integrate Jan's text suggestions
- [x] minor text adjustments
  - p1 "published annual reports" → published statistics based on
  - p1 add Roberts Surname
  - p1 move LOSH paragraph up
  - p4 add a mention that only the hardware license is considered
  - p4 add a line that no weak copyright projects have been found in the current dataset
  - p5 delete "[copy from publication]"
  - p12 "the best documentation" → amongst some of the best documentations
  - p12 delta stage available on LOSH as by WIF duplicate

[Ergänzungen LOSH-Report.docx](https://github.com/OPEN-NEXT/LOSH-Reporter/files/9576648/Erganzungen.LOSH-Report.docx)
[losh-report-08-2022_commented Robert_Jan.pdf](https://github.com/OPEN-NEXT/LOSH-Reporter/files/9576649/losh-report-08-2022_commented.Robert_Jan.pdf)

**Comment by hoijui** [comment]
all parts are now either done or markes as "won't-do" (striked through), thus closing.
