### ISSUE TITLE
concept losh reporter

### ISSUE THREAD

**Issue by traedamatic** [OPEN-NEXT/LOSH-Reporter#2]
- The LOSH reporter will b a python script.
- As template engine we will use Jinja 2 (https://jinja2docs.readthedocs.io/en/stable/)
- As graph lib we will use matplotlib (https://swcarpentry.github.io/python-novice-gapminder/09-plotting)
- The SPAREQL query is used to fill the template 
- A python script will execute a query against a Fuseski instance which is loaded with OSH RDF data.
-  poetry as dep manager is used
- 

A reporter package holds the logic for
- cli interaction
- fuseki querying  
- templating the md file 
- generate the PDF via pandoc

A queries are stored in a separate folder.

**Comment by hoijui** [comment]
This was done by NIcolas and working! :-)
(We now switched to a Jupyter-Lab impl)
