### ISSUE TITLE
Implement query logic for reporter

### ISSUE THREAD

**Issue by traedamatic** [OPEN-NEXT/LOSH-Reporter#4]
Implement query logic for reporter for apache fureseki

curl http://localhost:3030/vcard/ -X POST --data 'query=PREFIX+vCard%3A++++++%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2Fvcard-rdf%2F3.0%23%3E%0A%0ASELECT+%3Fy+%3FgivenName%0AWHERE%0A+%7B+%3Fy+vCard%3AFamily+%22Smith%22+.%0A+++%3Fy+vCard%3AGiven++%3FgivenName+.%0A+%7D' -H 'Accept: application/sparql-results+json,*/*;q=0.9'

**Comment by hoijui** [comment]
was also done by NIcolas already in the python impl, and was copied over to the Jupyter-Lab version
